name: Simply Handy
favicon: null
layout_spectrum: 0.64059
typography_spectrum: 0.37943
title: Simply Handy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#020000'
    - '#453027'
    - '#896647'
    - '#bc9779'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
