layout_spectrum: 1
typography_spectrum: 0.5806451
color:
  saturation: 0.5215054
  lightness: 0.5949821
  brandStrength: 1
  rhythmicContrast: 0.3080152
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Simply Handy
