name: Simply Handy
favicon: null
layout_spectrum: 0.26372
typography_spectrum: 0.72555
title: Simply Handy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#020000'
    - '#453027'
    - '#896647'
    - '#bc9779'
  brandStrength: 0.5
  lightness: 0.5949821
  saturation: 0.5215054
  rhythmicContrast: 0.3080152
purpose: []
