name: Simply Handy
favicon: null
layout_spectrum: 0
typography_spectrum: 0.72253
title: Simply Handy by John Kegel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#020000'
    - '#453027'
    - '#896647'
    - '#bc9779'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
